config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :job_edit
    end
  end
  resources :topics, only: [:new, :create, :destroy]

  resources :ownerships, only: [:create, :destroy]
  get 'rankings/good', to: 'rankings#good'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  def self.ranking
    self.group(:topic_id).order('count_topic_id DESC').limit(10).count(:topic_id)
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {maximum: 2000}
  validates :name, presence:  true, length: {maximum: 300}

  has_many :ownerships, dependent: :destroy
  has_many :users, through: :ownerships, dependent: :destroy



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics

  validates :name, presence: true, length: {maximum: 25 }
  validates :intro, length: {maximum: 500}
  validates :job, length: {maximum: 25}
  validates :school, presence: true, length: {maximum: 25}


  has_many :ownerships
  has_many :good_topics, through: :ownerships, source: :topic, dependent: :destroy

  def good(topic)
    self.ownerships.find_or_create_by(topic_id: topic.id)
  end

  def ungood(topic)
    good = self.ownerships.find_by(topic_id: topic.id)
    good.destroy if good
  end

  def good?(topic)
    self.good_topics.include?(topic)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:school])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:intro])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:job])
    devise_parameter_sanitizer.permit(:account_update, keys:[:intro])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if user_signed_in?
      @topics = Topic.all.order('created_at DESC').page(params[:page])

    end
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])
    current_user.good(@topic)
    redirect_to root_url
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    current_user.ungood(@topic)
    redirect_to root_url
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def good
    @ranking_counts = Ownership.ranking
    @topics = Topic.find(@ranking_counts.keys)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]
  def new
    @topic = current_user.topics.build
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      flash[:notice] = 'Topicを投稿しました。'
      redirect_to root_url
    else
      @topics = current_user.topics.order('created_at DESC').page(params[:page])
      flash.now[:alert] = 'Topicの投稿に失敗しました。'
      render 'topics/new'
    end
  end

  def destroy
    @topic.destroy
    flash[:success] = 'Topicを削除'
    redirect_back(fallback_location: root_path)
  end

  private
  def topic_params
    params.require(:topic).permit(:content, :name)
  end

  def correct_user
    @topic = current_user.topics.find_by(id: params[:id])
    unless @topic
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @count_goods = @user.ownerships.count
    @count_topics = @user.topics.count
    @topics = @user.topics.order('created_at DESC').page(params[:page])
  end
  def edit
    @user = current_user
  end
  def job_edit
    @user = current_user
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = '編集完了'
      redirect_to @user
    else
      flash[:alert] = '編集失敗'
      render 'users/edit'
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :intro, :job)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate_user!(opts={})
    opts[:scope] = :user
    warden.authenticate!(opts) if !devise_controller? || opts.delete(:force)
  end

  def user_signed_in?
    !!current_user
  end

  def current_user
    @current_user ||= warden.authenticate(:scope => :user)
  end

  def user_session
    current_user && warden.session(:user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/homes/index.html.erb
<div class="cover">
  <div class="cover-inner">
    <div class="cover-contents">
      <% unless user_signed_in? %>
        <h1>就活生のための掲示板</h1>
        <%= link_to 'Job Chainを始める', new_user_session_path, class: 'btn btn-dark btn-lg' %>
      <% end %>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <div class="header text-center">
    <h1>Home</h1>
  </div>
        <div class="row">

          <div class="offset-2 col-8">
          <%= render 'topics/topic', topics: @topics %>
          </div>
        </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice %>
  　　<p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Job Chain</a>

      <div class="collapse navbar-collapse justify-content-end" id="bs-example-navbar-collapse-1">
        <ul class="navbar-nav ">
          <% if user_signed_in? %>



            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item">
                  <%= link_to 'マイページ', user_path(current_user) %>
                </a>
                <a class="dropdown-item">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete  %>
                </a>
              </div>
            </li>

            <li class="nav-link text-light">
              <i class="fas fa-signal"></i> <a class="nav-ranking"><%= link_to 'Ranking',rankings_good_path  %></a>
            </li>


            <li class="nav-link text-light">
              <i class="fas fa-pen"></i> <%= link_to 'Topic投稿',new_topic_path %>
            </li>



          <% else %>
            <li class="nav-link">
            <a class="dropdown-menu"><%= link_to 'Login', new_user_session_path, class: 'post' %></a>
            </li>
            <li class="nav-link">
            <a class="dropdown-menu"><%= link_to 'Sign up',  new_user_registration_path, class: 'post' %></a>
            </li>
          <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>App share</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script>
        $('.dropdown-toggle').dropdown()
    </script>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= render 'layouts/flash' %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/ownerships/_good_button.html.erb
  <% if current_user.good?(topic) %>
    <%= form_for(topic.ownerships.find_by(user_id: current_user.id), html: {method: :delete}) do %>
      <%= hidden_field_tag :topic_id, topic.id %>
      <%= submit_tag 'Apathy', class: 'btn btn-danger btn-sm' %>
    <% end %>
  <%else %>
      <%= form_for(topic.ownerships.build) do %>
        <%= hidden_field_tag :topic_id, topic.id %>
        <%= submit_tag 'Empathy', class: 'btn btn-primary btn-sm' %>
      <% end %>
  <% end %>

app/views/ownerships/create.html.erb
<h1>Ownerships#create</h1>
<p>Find me in app/views/ownerships/create.html.erb</p>

app/views/ownerships/destroy.html.erb
<h1>Ownerships#destroy</h1>
<p>Find me in app/views/ownerships/destroy.html.erb</p>

app/views/rankings/good.html.erb
<div class="header text-center">
  <h1>人気Topic</h1>
</div>
<div class="row">
  <div class="offset-2 col-8">
      <% @topics.each_with_index do |topic, index| %>
        <div class="ranking">
          <div class="media">

            <img class="mr-3 img-rounded" src="<%= gravatar_url(topic.user, {size: 50}) %>" alt="">
          <div class="media-body">
            <%= link_to topic.user.name, user_path(topic.user) %> <span class="text-muted">posted at <%= topic.created_at %></span>
            <div>
              <p><%= topic.content %></p>
            </div>
            <div>
              <% unless current_user == topic.user %>
                <%= render 'ownerships/good_button', topic: topic %>
              <% end %>
            </div>
          </div>
            <div class="card-footer">
              <p class="text-center"><%= index+1 %>位: <%= @ranking_counts[topic.id] %> Empathy</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/_topic.html.erb
<ul class="topic-list">
  <% topics.each do |topic| %>
    <div class="media">
        <img class="mr-3" src="<%= gravatar_url(topic.user, {size: 50}) %>" alt="">
      <div class="media-body">
        Title: <strong><%= topic.name %></strong>

        <%= link_to topic.user.name, user_path(topic.user) %> <span class="text-muted">posted at <%= topic.created_at %></span>
        <div>
          <p><%= topic.content %></p>
        </div>
        <div>
          <% if current_user == topic.user %>
            <%= link_to "削除", topic, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% else %>
          <%= render 'ownerships/good_button', topic: topic %>
           <% end %>
        </div>
      </div>
      </div>
  <% end %>
  <%= paginate topics %>
</ul>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/new.html.erb
<div class="container">
<div class="row">
  <div class="offset-3 col-6">
    <div class="card">
      <div class="card-header">Topic投稿</div>
      <div class="card-body">

        <%= form_for(@topic) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'Title' %><br />
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :content, 'Topic' %><br />
            <%= f.text_area :content, class: 'form-control', rows: 10 %>
          </div>

          <div class="actions">
            <%= f.submit "topicを作成", class: 'btn btn-primary' %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
  <div class="offset-3 col-6">
    <div class="card">
      <div class="card-header">自己紹介の編集</div>
      <div class="card-body">
        <%= form_for(@user) do |f| %>

          <div class="form-group">
            <%= f.label :intro, '自己紹介' %>
            <%= f.text_area :intro, class: 'form-control', rows: 10 %>
          </div>


          <div class="text-right">
            <%= f.submit '編集する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/job_edit.html.erb
<div class="row">
  <div class="offset-3 col-6">
    <div class="card">
      <div class="card-header">志望業界または企業・職種の編集</div>
      <div class="card-body">
        <%= form_for(@user) do |f| %>

          <div class="form-group">
            <%= f.text_field :job, class: 'form-control' %>
          </div>


          <div class="text-right">
            <%= f.submit '編集する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user_show">
<div class="row">
  <div class="col-md-6">
    <div class="profile1">
      <strong>ユーザ名</strong><br>
    </div>
    <%= @user.name %>
    <div class="profile1">
      <strong>在籍している大学or専門学校</strong><br>
    </div>
    <%= @user.school %>
    <div class="profile1">
      <strong>志望業界または企業・職種</strong> <%= link_to '編集',  job_edit_user_path, class: 'btn btn-default btn-xs' %><br>
    </div>
    <%= @user.job %>
    <div class="profile1">
      <strong>自己紹介</strong> <%= link_to '編集',  edit_user_path, class: 'btn btn-default btn-xs' %><br>
    </div>
    <%= @user.intro %>
  </div>
  <div class="col-md-6">
    <div class="user-profile">
      <div class="icon text-center">
        <img src="<%= gravatar_url(current_user, size: 100) %>" alt="" class="img-circle">
      </div>
      <div class="status text-center">
        <ul>
          <li>
            <div class="status-label">Empathy</div>
            <div id="good_count" class="status-value">
              <%= @count_goods %>
            </div>
          </li>
          <li>
            <div class="status-label">Your Topic</div>
            <div id="topic_count" class="status-value">
              <%= @count_topics %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="text-center">
      <h3>投稿歴</h3>
    </div>
    <div>
      <%= render 'topics/topic', topics: @topics %>
    </div>
  </div>
</div>
</div>